### ISSUE TITLE
error: cannot convert value of type 'String.SubSequence' (aka 'Substring') to expected argument type 'String'

### ISSUE THREAD

**Issue by ehmjaysee** [StatusQuo/spmready#2]
MacOS 10.14.6
xcode 10.3

$ ./spmready.swift 
./spmready.swift:25:9: warning: string literal is unused
        "\(self.readyOrNot()) | \(self.name) : \(self.repo ?? "not found")"
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./spmready.swift:55:107: error: cannot convert value of type 'String.SubSequence' (aka 'Substring') to expected argument type 'String'
            if  let match = regex.matches(String(line)), let podNameRange = Range(match.range(at: 1), in: line) {
                                                                                                          ^~~~
                                                                                                          String( )

**Comment by alessioarsuffi** [comment]
Same error for me, MacOs 10.14.5
Xcode 10.3

**Comment by StatusQuo** [comment]
@ehmjaysee hi thanks for the feedback. i couldn't really reconstruct this issue but please try with the new version :)

**Comment by ehmjaysee** [comment]
Same error with the new version.  I debugged the issue and found a problem in fetchPods().  Notice the loop is iterating over lines[] and variable "line" is a substring. The "if" statement on line 55 tries to create a range using "line" in some places but String(line) in others. Then line 56 uses the substring again. 

Here is one way to fix this by creating a single String from line and using it consistently:

```
func fetchPods(_ path: String) -> [Pod]? {
    var pods:[Pod] = []
    do {
        // Get the contents
        let contents = try String(contentsOfFile: path, encoding: .utf8)
        let lines = contents.split(separator: "\n")
        for line in lines {
            let regex = NSRegularExpression("pod '([A-Za-z0-9-]*)'")
            let lineString = String(line)

            if  let match = regex.matches(lineString), let podNameRange = Range(match.range(at: 1), in: lineString) {
                let podName = lineString[podNameRange]
                pods.append(Pod(name: String(podName)))
            }
        }
        //sprint(contents)
    }
    catch {
        print("Failed to open Podfile at \(path)")
        print("make sure the file exists")
        return nil
    }
    return pods

}

```

**Comment by ehmjaysee** [comment]
When the above issue is fixed the warning on line 25 becomes an error: 

```
$ ./spmready.swift 
./spmready.swift:25:9: warning: string literal is unused
        "\(self.readyOrNot()) | \(self.name) : \(self.repo ?? "not found")"
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./spmready.swift:26:5: error: missing return in a function expected to return 'String'
    }

```    

The fix is trivial.  Add a "return" before the string:

```
    func format() -> String {
        return "\(self.readyOrNot()) | \(self.name) : \(self.repo ?? "not found")"
    }

```

**Comment by StatusQuo** [comment]
@ehmjaysee great! thank you very much. I just added your code :)

**Comment by backslash-f** [comment]
Just to mention that I got the exact same issue but I was able to fix it by choosing Xcode 11 as `Command Line Tools` under `Xcode / Preferences / Locations`:

<img width="358" alt="cli" src="https://user-images.githubusercontent.com/664951/64887151-412e3180-d668-11e9-8645-7b2d271dfbee.png">

Also, for me, it only runs in Catalina (10.15+). Below that, it gave me some error regarding some `init` function. ¯\_(ツ)_/¯ 

Anyway, good job on this script. 👍🏻

**Comment by kevinrenskers** [comment]
```
$ ./spmready.swift 
./spmready.swift:25:9: warning: string literal is unused
        "\(self.readyOrNot()) | \(self.name) : \(self.repo ?? "not found")"
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./spmready.swift:55:107: error: cannot convert value of type 'String.SubSequence' (aka 'Substring') to expected argument type 'String'
            if  let match = regex.matches(String(line)), let podNameRange = Range(match.range(at: 1), in: line) {
                                                                                                          ^~~~
                                                                                                          String( )
```

still getting this today

**Comment by StatusQuo** [comment]
@kevinrenskers sorry the readme linked to the old script version. Should be finally fixed now
