### ISSUE TITLE
Broken link in medium post

### ISSUE THREAD

**Issue by guillaumealgis** [StatusQuo/spmready#5]
Hi,

The link in your medium post here is broken : https://medium.com/@bastihumann/ready-for-swift-package-manger-3defcca50ca3

The current link in the curl command is 

```
https://raw.githubusercontent.com/StatusQuo/spmready/master/spmready/main.swift
```

but it should be

```
https://raw.githubusercontent.com/StatusQuo/spmready/master/main.swift
```

**Comment by StatusQuo** [comment]
thank you for reporting, fixed.
